### ISSUE TITLE
Simplify site deployment

### ISSUE THREAD

**Issue by literarymachine** [rightsstatements/rights-deploy#18]
Currently http://rightsstatements.github.io/ is used as the staging / draft CMS. Any modifications have to manually be deployed to production once merged. It would greatly simplify the process to reverse proxy http://rightsstatements.github.io/ to http://rightsstatements.org, i.e. use GitHub pages as the production CMS. Drafts could still easily be created by forking the CMS to another account, such as http://literarymachine.github.io/rightsstatements.github.io/. Pull requests could then be done from the fork, and once merged they would automatically be deployed. A couple of changes to the Jekyll setup would be necessary though; see https://github.com/rightsstatements/rightsstatements.github.io/compare/master...literarymachine:master

**Comment by aisaac** [comment]
@literarymachine it looks like a smart idea and could be interesting, especially for @anarchivist and I. I have several doubts however:

1. there are currently at least two people (Paul and Julia) who have made (or could make) edits on the site, whom I'm not sure will be appreciate the extra forking step in their workflow. Maybe others will not be so keen on doing this either.

2. When I (finally) finally managed to first deploy the CMS myself some time ago, I realized that the page I had wanted to update (http://rights-stg.rightsstatements.org/page/1.0/?language=en) was not updated. @anarchivist had me redeploy the entire app, which worked. How would your suggested changes play for this case?

3. I'm not sure it's wise to change the process at a stage we're discussing adding features in 2018. Though I realize that the changes you're suggesting are not a lot of work...
