### ISSUE TITLE
Configure HTTPS

### ISSUE THREAD

**Issue by literarymachine** [rightsstatements/rights-deploy#20]
- [x] a2enmod ssl
- [x] New vhost config for `*:443`
- [x] Update vhost config for `*:80` to redirect to `https`

**Comment by literarymachine** [comment]
@anarchivist I have done the above manually on staging, see e.g. https://rights-stg.rightsstatements.org/page/1.0/?language=en and in general it works. See https://github.com/rightsstatements/rightsstatements.github.io/pull/154 for some minor adjustments. I am now looking into how to best reflect this in our ansible configuration. Would manually placing the necessary key / cert on the server and simply setting the path in the config be an option? I would argue the key best never leaves the server.

**Comment by anarchivist** [comment]
> Would manually placing the necessary key / cert on the server and simply setting the path in the config be an option? I would argue the key best never leaves the server.

I would agree with this, and I like the approach you propose.

**Comment by aisaac** [comment]
I am not a big expert on this but you have my support for this (says the one who is probably going to have to generate a new personal key for himself and ask @anarchivist to manually put it on the server)
